version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
    - "pr: dependency-update"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
    - "pr: dependency-update"
